# fly.toml app configuration file generated for coachly on 2025-04-24T20:47:39+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'coachly'
primary_region = 'cdg'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
